#!/bin/sh 
if [ $# -eq 0 ] ; then
  echo "Usage --- svn-amend <package_name> <revision number>"
  echo "eg: svn-amend myki-br r92741"
else
  svn propedit -r $2 --revprop svn:log https://auperasvn01.aupera.erggroup.com/svn/DPG_SWBase/$1/trunk
fi
